services:
  database:
    image: mysql:8.0
    platform: linux/amd64  # Ajout de cette ligne
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db_landing
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
