name: Deploy Symfony app to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute SSH command
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "SSH connection successful!"
            cd /var/www/landing-competition/
            echo "Pulling latest changes from Git..."
            git reset --hard HEAD
            git pull origin main --rebase
            echo "Installing dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader
            echo "Running database migrations..."
            php bin/console cache:clear --no-warmup
            php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
            php bin/console cache:warmup
            echo "Installing assets..."
            php bin/console assets:install
            echo "Building assets..."
            npm install
            npm run build
            php bin/console cache:clear
            echo "Reloading Nginx..."
            sudo systemctl reload nginx

